"""Data models for the SOC triage bot."""

from .action import Action, ActionType
from .ai_overlay import (
    AINextCheck,
    AIOverlay,
    AISimilarCaseNarrative,
    AIStatement,
    AITrackInterpretation,
    StatementType,
    TPFPLikelihood,
)
from .enrichment import (
    EnrichmentResult,
    EnrichmentStatus,
    ExtractedEntity,
    ExtractedIndicator,
)
from .signal import (
    ArtifactContext,
    DetectionContext,
    EntityBehaviorContext,
    Signal,
    SignalSource,
    SignalType,
    VulnerabilityContext,
)
from .triage_report import (  # Signal type extensions; Forecast models; Classification; Similar cases; Recommendations; Signal context; Enrichment bundle; Executive summary; Metadata; Normalized signal; Top-level report; Track config
    SIGNAL_TYPE_TRACK_CONFIGS,
    AssetContext,
    ClassificationLabel,
    ClassificationResult,
    EnrichmentBundle,
    EnrichmentNotes,
    EntityFocus,
    EnvironmentExposure,
    ExecutiveSummary,
    ExtendedSignalType,
    ForecastBacktest,
    ForecastBundle,
    ForecastHorizonMetrics,
    ForecastHorizonResult,
    ForecastHorizonThresholds,
    ForecastLatest,
    ForecastSeasonality,
    ForecastTrack,
    ForecastTracks,
    HostContext,
    HostVulnerability,
    LocalSighting,
    MitreMapping,
    NormalizedSignal,
    Recommendation,
    RelatedEvent,
    ReportMeta,
    ScopeAssessment,
    SignalContext,
    SignalTypeTrackConfig,
    SimilarCase,
    ThreatIntelEntry,
    TrackEntityConfig,
    TriageReport,
    UserContext,
    get_track_config,
)

__all__ = [
    # Signal models (extended)
    "Signal",
    "SignalType",
    "SignalSource",
    "DetectionContext",
    "ArtifactContext",
    "EntityBehaviorContext",
    "VulnerabilityContext",
    # Enrichment
    "EnrichmentResult",
    "EnrichmentStatus",
    "ExtractedEntity",
    "ExtractedIndicator",
    # Classification
    "ClassificationLabel",
    # Action
    "Action",
    "ActionType",
    # AI Overlay
    "AIOverlay",
    "AINextCheck",
    "AISimilarCaseNarrative",
    "AIStatement",
    "AITrackInterpretation",
    "StatementType",
    "TPFPLikelihood",
    # Triage Report (new structured models)
    "ExtendedSignalType",
    "ForecastHorizonMetrics",
    "ForecastHorizonThresholds",
    "ForecastHorizonResult",
    "ForecastBacktest",
    "ForecastLatest",
    "ForecastTrack",
    "ForecastSeasonality",
    "ForecastTracks",
    "ForecastBundle",
    "MitreMapping",
    "ClassificationResult",
    "SimilarCase",
    "Recommendation",
    "EntityFocus",
    "SignalContext",
    "LocalSighting",
    "ScopeAssessment",
    "ThreatIntelEntry",
    "HostContext",
    "UserContext",
    "AssetContext",
    "HostVulnerability",
    "EnvironmentExposure",
    "RelatedEvent",
    "EnrichmentNotes",
    "EnrichmentBundle",
    "ExecutiveSummary",
    "ReportMeta",
    "NormalizedSignal",
    "TriageReport",
    "TrackEntityConfig",
    "SignalTypeTrackConfig",
    "SIGNAL_TYPE_TRACK_CONFIGS",
    "get_track_config",
]
