"""Report generation service using Jinja templates."""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Environment, FileSystemLoader, Template

from ..models import Action, AIOverlay, Classification, EnrichmentResult, Signal

# Default template directory (relative to this file)
DEFAULT_TEMPLATE_DIR = Path(__file__).parent.parent / "templates"


class ReportService:
    """Service for rendering triage reports."""

    def __init__(self, template_dir: Optional[str] = None):
        """Initialize report service.

        Args:
            template_dir: Directory containing Jinja templates.
                         If not provided, uses the default templates directory.
        """
        if template_dir:
            self.template_path = Path(template_dir)
        else:
            self.template_path = DEFAULT_TEMPLATE_DIR

        # Initialize Jinja environment with template directory
        if self.template_path.exists():
            self.env = Environment(loader=FileSystemLoader(str(self.template_path)))
        else:
            self.env = None

    def generate_report(
        self,
        signal: Signal,
        enrichments: Dict[str, EnrichmentResult],
        classification: Classification,
        actions: List[Action],
        forecast_data: Optional[Dict[str, Any]] = None,
        similar_cases: Optional[List[tuple]] = None,
        ai_overlay: Optional[AIOverlay] = None,
    ) -> str:
        """Generate Markdown triage report.

        Args:
            signal: The signal
            enrichments: Enrichment results
            classification: Classification result
            actions: Proposed actions
            forecast_data: Optional forecast data
            similar_cases: Optional similar cases
            ai_overlay: Optional AI overlay data (LLM-generated summaries/explanations)

        Returns:
            Markdown report string
        """
        # Prepare data for template
        context = {
            "signal": signal,
            "enrichments": enrichments,
            "classification": classification,
            "actions": actions,
            "forecast_data": forecast_data or {},
            "similar_cases": similar_cases or [],
            "ai_overlay": ai_overlay,  # None if AI not enabled
            "now": datetime.now(timezone.utc),
        }

        template = self._get_template()
        return template.render(**context)

    def _get_template(self) -> Template:
        """Get the report template.

        Returns:
            Jinja2 Template object for rendering the report.
        """
        if self.env:
            try:
                return self.env.get_template("triage_report.md.j2")
            except Exception:
                pass

        # Fallback: minimal inline template if external template not available
        return Template(self._get_fallback_template())

    def _get_fallback_template(self) -> str:
        """Get a minimal fallback template if external template is not available."""
        return """# SOC Triage Report – {{ signal.signal_id }}

## Decision Banner

> **Triage Decision:** **{{ classification.label.value.upper() }}**
> **Confidence:** **{{ "%.0f"|format(classification.confidence * 100) }}%**

## Signal Information

- **Type:** {{ signal.signal_type.value }}
- **Title:** {{ signal.title }}
- **Severity:** {{ signal.severity }}
- **Timestamp:** {{ signal.timestamp.isoformat() }}

## Classification

- **Label:** {{ classification.label.value.upper() }}
- **Confidence:** {{ "%.0f"|format(classification.confidence * 100) }}%

### Reasoning
{% for reason in classification.reasoning %}
- {{ reason }}
{% endfor %}

## Recommended Actions

{% for action in actions %}
### {{ loop.index }}. {{ action.title }} (Priority {{ action.priority }})

{{ action.description }}

{% endfor %}

*Generated by SOC Triage Bot*
"""
